version: '3.9'
services:
  readme.user.mongo:
    image: mongo:4.4
    restart: always
    container_name: readme.user.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - 27017:27017

    volumes:
      - readme.mongo.user:/data/db

  readme.user.mongo.ui:
    image: mongo-express:1.0.2-20
    restart: always
    container_name: readme.user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@readme.user.mongo:${MONGO_PORT}/

volumes:
  readme.mongo.user:
